import { MinecraftTriggerFiltered } from '@minecraft/MinecraftTriggerFiltered';
import { MinecraftFilters } from '@minecraft/types/MinecraftFilters';
import { SpellEffects } from './components/SpellEffects';
import { Addrider } from './components/Addrider';
import { AdmireItem } from './components/AdmireItem';
import { Ageable } from './components/Ageable';
import { AmbientSoundInterval } from './components/AmbientSoundInterval';
import { Angry } from './components/Angry';
import { AnnotationBreakDoor } from './components/AnnotationBreakDoor';
import { AreaAttack } from './components/AreaAttack';
import { AttackCooldown } from './components/AttackCooldown';
import { Barter } from './components/Barter';
import { BlockSensor } from './components/BlockSensor';
import { Boostable } from './components/Boostable';
import { Boss } from './components/Boss';
import { BreakBlocks } from './components/BreakBlocks';
import { Breathable } from './components/Breathable';
import { Breedable } from './components/Breedable';
import { Bribeable } from './components/Bribeable';
import { Buoyant } from './components/Buoyant';
import { CelebrateHunt } from './components/CelebrateHunt';
import { CollisionBox } from './components/CollisionBox';
import { Color } from './components/Color';
import { CombatRegeneration } from './components/CombatRegeneration';
import { ConditionalBandwidthOptimization } from './components/ConditionalBandwidthOptimization';
import { CustomHitTest } from './components/CustomHitTest';
import { DamageOverTime } from './components/DamageOverTime';
import { DamageSensor } from './components/DamageSensor';
import { DefaultLookAngle } from './components/DefaultLookAngle';
import { Despawn } from './components/Despawn';
import { DryingOutTimer } from './components/DryingOutTimer';
import { EconomyTradeTable } from './components/EconomyTradeTable';
import { EntitySensor } from './components/EntitySensor';
import { EnvironmentSensor } from './components/EnvironmentSensor';
import { Equippable } from './components/Equippable';
import { ExperienceReward } from './components/ExperienceReward';
import { Explode } from './components/Explode';
import { Flocking } from './components/Flocking';
import { FlyingSpeed } from './components/FlyingSpeed';
import { FrictionModifier } from './components/FrictionModifier';
import { Genetics } from './components/Genetics';
import { Giveable } from './components/Giveable';
import { GroundOffset } from './components/GroundOffset';
import { GroupSize } from './components/GroupSize';
import { GrowsCrop } from './components/GrowsCrop';
import { Healable } from './components/Healable';
import { Home } from './components/Home';
import { HurtOnCondition } from './components/HurtOnCondition';
import { InsideBlockNotifier } from './components/InsideBlockNotifier';
import { Insomnia } from './components/Insomnia';
import { InstantDespawn } from './components/InstantDespawn';
import { Interact } from './components/Interact';
import { Inventory } from './components/Inventory';
import { IsDyeable } from './components/IsDyeable';
import { ItemControllable } from './components/ItemControllable';
import { JumpStatic } from './components/JumpStatic';
import { Leashable } from './components/Leashable';
import { LookAt } from './components/LookAt';
import { Loot } from './components/Loot';
import { MarkVariant } from './components/MarkVariant';
import { MobEffect } from './components/MobEffect';
import { Movement } from './components/Movement';
import { MovementJump } from './components/MovementJump';
import { MovementSway } from './components/MovementSway';
import { Nameable } from './components/Nameable';
import { Navigation } from './components/Navigation';
import { Peek } from './components/Peek';
import { Physics } from './components/Physics';
import { PreferredPath } from './components/PreferredPath';
import { Projectile } from './components/Projectile';
import { Pushable } from './components/Pushable';
import { PushThrough } from './components/PushThrough';
import { RaidTrigger } from './components/RaidTrigger';
import { RailMovement } from './components/RailMovement';
import { RailSensor } from './components/RailSensor';
import { RavagerBlocked } from './components/RavagerBlocked';
import { Rideable } from './components/Rideable';
import { Scale } from './components/Scale';
import { ScaleByAge } from './components/ScaleByAge';
import { Scheduler } from './components/Scheduler';
import { Shareables } from './components/Shareables';
import { Shooter } from './components/Shooter';
import { Sittable } from './components/Sittable';
import { SkinId } from './components/SkinId';
import { SoundVolume } from './components/SoundVolume';
import { SpawnEntity } from './components/SpawnEntity';
import { Strength } from './components/Strength';
import { Tameable } from './components/Tameable';
import { TameMount } from './components/TameMount';
import { TargetNearbySensor } from './components/TargetNearbySensor';
import { Teleport } from './components/Teleport';
import { TickWorld } from './components/TickWorld';
import { Timer } from './components/Timer';
import { TradeTable } from './components/TradeTable';
import { Trail } from './components/Trail';
import { Transformation } from './components/Transformation';
import { Trusting } from './components/Trusting';
import { TypeFamily } from './components/TypeFamily';
import { Variant } from './components/Variant';
import { WalkAnimationSpeed } from './components/WalkAnimationSpeed';
import { WaterMovement } from './components/WaterMovement';
import { Attack } from './components/Attack';
import { BehaviorAdmireItem } from './components/BehaviorAdmireItem';
import { BehaviorBeg } from './components/BehaviorBeg';
import { BehaviorBreed } from './components/BehaviorBreed';
import { BehaviorDefendTrustedTarget } from './components/BehaviorDefendTrustedTarget';
import { BehaviorDrinkPotion } from './components/BehaviorDrinkPotion';
import { BehaviorEatCarriedItem } from './components/BehaviorEatCarriedItem';
import { BehaviorExploreOutskirts } from './components/BehaviorExploreOutskirts';
import { BehaviorFindCover } from './components/BehaviorFindCover';
import { BehaviorFindMount } from './components/BehaviorFindMount';
import { BehaviorFindUnderwaterTreasure } from './components/BehaviorFindUnderwaterTreasure';
import { BehaviorFleeSun } from './components/BehaviorFleeSun';
import { BehaviorFloatWander } from './components/BehaviorFloatWander';
import { BehaviorFollowCaravan } from './components/BehaviorFollowCaravan';
import { BehaviorFollow } from './components/BehaviorFollow';
import { BehaviorFollowParent } from './components/BehaviorFollowParent';
import { BehaviorFollowTargetCaptain } from './components/BehaviorFollowTargetCaptain';
import { BehaviorGoHome } from './components/BehaviorGoHome';
import { BehaviorHide } from './components/BehaviorHide';
import { BehaviorHoldGround } from './components/BehaviorHoldGround';
import { BehaviorHurtByTarget } from './components/BehaviorHurtByTarget';
import { BehaviorInspectBookshelf } from './components/BehaviorInspectBookshelf';
import { BehaviorKnockbackRoar } from './components/BehaviorKnockbackRoar';
import { BehaviorLayDown } from './components/BehaviorLayDown';
import { BehaviorLayEgg } from './components/BehaviorLayEgg';
import { BehaviorLeapAtTarget } from './components/BehaviorLeapAtTarget';
import { BehaviorLook } from './components/BehaviorLook';
import { BehaviorMingle } from './components/BehaviorMingle';
import { BehaviorMountPathing } from './components/BehaviorMountPathing';
import { BehaviorMoveThroughVillage } from './components/BehaviorMoveThroughVillage';
import { BehaviorMoveToBlock } from './components/BehaviorMoveToBlock';
import { BehaviorMove } from './components/BehaviorMove';
import { BehaviorMoveToLiquid } from './components/BehaviorMoveToLiquid';
import { BehaviorMoveToPoi } from './components/BehaviorMoveToPoi';
import { BehaviorMoveToRandomBlock } from './components/BehaviorMoveToRandomBlock';
import { BehaviorMoveToVillage } from './components/BehaviorMoveToVillage';
import { BehaviorMoveTowardsTarget } from './components/BehaviorMoveTowardsTarget';
import { BehaviorNap } from './components/BehaviorNap';
import { BehaviorOcelotSitOnBlock } from './components/BehaviorOcelotSitOnBlock';
import { BehaviorOpenDoor } from './components/BehaviorOpenDoor';
import { BehaviorHurtTarget } from './components/BehaviorHurtTarget';
import { BehaviorPanic } from './components/BehaviorPanic';
import { BehaviorPetSleepWithOwner } from './components/BehaviorPetSleepWithOwner';
import { BehaviorPickupItems } from './components/BehaviorPickupItems';
import { BehaviorPlay } from './components/BehaviorPlay';
import { BehaviorRaidGarden } from './components/BehaviorRaidGarden';
import { BehaviorAttackableTarget } from './components/BehaviorAttack';
import { BehaviorRandomBreach } from './components/BehaviorRandomBreach';
import { BehaviorRandomFly } from './components/BehaviorRandomFly';
import { BehaviorRandomHover } from './components/BehaviorRandomHover';
import { BehaviorRandomLookAround } from './components/BehaviorRandomLookAround';
import { BehaviorRandomLookAroundAndSit } from './components/BehaviorRandomLookAroundAndSit';
import { BehaviorRandomSitting } from './components/BehaviorRandomSitting';
import { BehaviorRandomStroll } from './components/BehaviorRandomStroll';
import { BehaviorRandomSwim } from './components/BehaviorRandomSwim';
import { BehaviorRiseToLiquidLevel } from './components/BehaviorRiseToLiquidLevel';
import { BehaviorRoll } from './components/BehaviorRoll';
import { BehaviorRunAroundLikeCrazy } from './components/BehaviorRunAroundLikeCrazy';
import { BehaviorScared } from './components/BehaviorScared';
import { BehaviorSendEvent } from './components/BehaviorSendEvent';
import { BehaviorShareItems } from './components/BehaviorShareItems';
import { BehaviorSkeletonHorseTrap } from './components/BehaviorSkeletonHorseTrap';
import { BehaviorSleep } from './components/BehaviorSleep';
import { BehaviorSlimeAttack } from './components/BehaviorSlimeAttack';
import { BehaviorSnacking } from './components/BehaviorSnacking';
import { BehaviorSneeze } from './components/BehaviorSneeze';
import { BehaviorStalkAndPounceOnTarget } from './components/BehaviorStalkAndPounceOnTarget';
import { BehaviorStompTurtleEgg } from './components/BehaviorStompTurtleEgg';
import { BehaviorStrollTowardsVillage } from './components/BehaviorStrollTowardsVillage';
import { BehaviorSummonEntity } from './components/BehaviorSummonEntity';
import { BehaviorSwell } from './components/BehaviorSwell';
import { BehaviorTempt } from './components/BehaviorTempt';
import { BehaviorTradeInterest } from './components/BehaviorTradeInterest';
import { BehaviorVexCopyOwnerTarget } from './components/BehaviorVexCopyOwnerTarget';
import { BehaviorWitherTargetHighestDamage } from './components/BehaviorWitherTargetHighestDamage';
import { BehaviorWork } from './components/BehaviorWork';

// Description
export interface EntityDescription {
  /** @pattern ^(?:(?:(?!minecraft|minecon))+[a-z]*:[a-z_]*)+$ */
  identifier: string;
  is_spawnable?: boolean;
  is_summonable?: boolean;
  is_experimental?: boolean;
  runtime_identifier?: string;
  animations?: AnimationProperties;
  scripts?: ScriptProperties;
}

// Properties
export interface AnimationProperties {
  [property_name: string]: string;
}

export interface ScriptProperties {
  animate: string[];
}

// Components
export interface ComponentGroups {
  [property_name: string]: EntityComponents;
}

export interface EntityComponents {
  ['minecraft:addrider']?: Addrider;
  ['minecraft:admire_item']?: AdmireItem;
  ['minecraft:ageable']?: Ageable;
  ['minecraft:angry']?: Angry;
  ['minecraft:annotation.break_door']?: AnnotationBreakDoor;
  ['minecraft:annotation.open_door']?: any;
  ['minecraft:area_attack']?: AreaAttack;
  ['minecraft:attack']?: Attack;
  ['minecraft:attack_cooldown']?: AttackCooldown;
  ['minecraft:barter']?: Barter;
  ['minecraft:block_climber']?: any;
  ['minecraft:block_sensor']?: BlockSensor;
  ['minecraft:boostable']?: Boostable;
  ['minecraft:boss']?: Boss;
  ['minecraft:break_blocks']?: BreakBlocks;
  ['minecraft:breathable']?: Breathable;
  ['minecraft:breedable']?: Breedable;
  ['minecraft:bribeable']?: Bribeable;
  ['minecraft:buoyant']?: Buoyant;
  ['minecraft:burns_in_daylight']?: any;
  ['minecraft:celebrate_hunt']?: CelebrateHunt;
  ['minecraft:combat_regeneration']?: CombatRegeneration;
  ['minecraft:conditional_bandwidth_optimization']?: ConditionalBandwidthOptimization;
  ['minecraft:custom_hit_test']?: CustomHitTest;
  ['minecraft:damage_over_time']?: DamageOverTime;
  ['minecraft:damage_sensor']?: DamageSensor;
  ['minecraft:despawn']?: Despawn;
  ['minecraft:drying_out_timer']?: DryingOutTimer;
  ['minecraft:economy_trade_table']?: EconomyTradeTable;
  ['minecraft:entity_sensor']?: EntitySensor;
  ['minecraft:environment_sensor']?: EnvironmentSensor;
  ['minecraft:equip_item']?: any;
  ['minecraft:equippable']?: Equippable;
  ['minecraft:experience_reward']?: ExperienceReward;
  ['minecraft:explode']?: Explode;
  ['minecraft:flocking']?: Flocking;
  ['minecraft:genetics']?: Genetics;
  ['minecraft:giveable']?: Giveable;
  ['minecraft:group_size']?: GroupSize;
  ['minecraft:grows_crop']?: GrowsCrop;
  ['minecraft:healable']?: Healable;
  ['minecraft:home']?: Home;
  ['minecraft:hurt_on_condition']?: HurtOnCondition;
  ['minecraft:inside_block_notifier']?: InsideBlockNotifier;
  ['minecraft:insomnia']?: Insomnia;
  ['minecraft:instant_despawn']?: InstantDespawn;
  ['minecraft:interact']?: Interact;
  ['minecraft:inventory']?: Inventory;
  ['minecraft:item_hopper']?: any;
  ['minecraft:jump.dynamic']?: any;
  ['minecraft:jump.static']?: JumpStatic;
  ['minecraft:leashable']?: Leashable;
  ['minecraft:lookat']?: LookAt;
  ['minecraft:managed_wandering_trader']?: any;
  ['minecraft:mob_effect']?: MobEffect;
  ['minecraft:movement.amphibious']?: Movement;
  ['minecraft:movement.basic']?: Movement;
  ['minecraft:movement.fly']?: Movement;
  ['minecraft:movement.generic']?: Movement;
  ['minecraft:movement.hover']?: Movement;
  ['minecraft:movement.jump']?: MovementJump;
  ['minecraft:movement.skip']?: Movement;
  ['minecraft:movement.sway']?: MovementSway;
  ['minecraft:nameable']?: Nameable;
  ['minecraft:navigation.climb']?: Navigation;
  ['minecraft:navigation.float']?: Navigation;
  ['minecraft:navigation.fly']?: Navigation;
  ['minecraft:navigation.generic']?: Navigation;
  ['minecraft:navigation.hover']?: Navigation;
  ['minecraft:navigation.swim']?: Navigation;
  ['minecraft:navigation.walk']?: Navigation;
  ['minecraft:out_of_control']?: any;
  ['minecraft:peek']?: Peek;
  ['minecraft:persistent']?: any;
  ['minecraft:physics']?: Physics;
  ['minecraft:preferred_path']?: PreferredPath;
  ['minecraft:projectile']?: Projectile;
  ['minecraft:pushable']?: Pushable;
  ['minecraft:raid_trigger']?: RaidTrigger;
  ['minecraft:rail_movement']?: RailMovement;
  ['minecraft:rail_sensor']?: RailSensor;
  ['minecraft:ravager_blocked']?: RavagerBlocked;
  ['minecraft:rideable']?: Rideable;
  ['minecraft:scale_by_age']?: ScaleByAge;
  ['minecraft:scheduler']?: Scheduler;
  ['minecraft:shareables']?: Shareables;
  ['minecraft:shooter']?: Shooter;
  ['minecraft:sittable']?: Sittable;
  ['minecraft:spawn_entity']?: SpawnEntity;
  ['minecraft:spell_effects']?: SpellEffects;
  ['minecraft:strength']?: Strength;
  ['minecraft:tameable']?: Tameable;
  ['minecraft:tamemount']?: TameMount;
  ['minecraft:target_nearby_sensor']?: TargetNearbySensor;
  ['minecraft:teleport']?: Teleport;
  ['minecraft:tick_world']?: TickWorld;
  ['minecraft:timer']?: Timer;
  ['minecraft:trade_table']?: TradeTable;
  ['minecraft:trail']?: Trail;
  ['minecraft:transformation']?: Transformation;
  ['minecraft:trusting']?: Trusting;
  ['minecraft:water_movement']?: WaterMovement;

  // Property Components
  ['minecraft:ambient_sound_interval']?: AmbientSoundInterval;
  ['minecraft:can_climb']?: object;
  ['minecraft:can_fly']?: any;
  ['minecraft:can_power_jump']?: any;
  ['minecraft:collision_box']?: CollisionBox;
  ['minecraft:color']?: Color;
  ['minecraft:color2']?: Color;
  ['minecraft:default_look_angle']?: DefaultLookAngle;
  ['minecraft:equipment']?: any;
  ['minecraft:fire_immune']?: any;
  ['minecraft:floats_in_liquid']?: any;
  ['minecraft:flying_speed']?: FlyingSpeed;
  ['minecraft:friction_modifier']?: FrictionModifier;
  ['minecraft:ground_offset']?: GroundOffset;
  ['minecraft:input_ground_controlled']?: any;
  ['minecraft:is_baby']?: any;
  ['minecraft:is_charged']?: any;
  ['minecraft:is_chested']?: any;
  ['minecraft:is_dyeable']?: IsDyeable;
  ['minecraft:is_hidden_when_invisible']?: any;
  ['minecraft:is_ignited']?: any;
  ['minecraft:is_illager_captain']?: any;
  ['minecraft:is_saddled']?: any;
  ['minecraft:is_shaking']?: any;
  ['minecraft:is_sheared']?: any;
  ['minecraft:is_stackable']?: any;
  ['minecraft:is_stunned']?: any;
  ['minecraft:is_tamed']?: any;
  ['minecraft:item_controllable']?: ItemControllable;
  ['minecraft:loot']?: Loot;
  ['minecraft:mark_variant']?: MarkVariant;
  ['minecraft:push_through']?: PushThrough;
  ['minecraft:scale']?: Scale;
  ['minecraft:skin_id']?: SkinId;
  ['minecraft:sound_volume']?: SoundVolume;
  ['minecraft:type_family']?: TypeFamily;
  ['minecraft:variant']?: Variant;
  ['minecraft:walk_animation_speed']?: WalkAnimationSpeed;

  // Trigger Components
  ['minecraft:on_death']?: MinecraftTriggerFiltered;
  ['minecraft:on_friendly_anger']?: MinecraftTriggerFiltered;
  ['minecraft:on_hurt']?: MinecraftTriggerFiltered;
  ['minecraft:on_hurt_by_player']?: MinecraftTriggerFiltered;
  ['minecraft:on_ignite']?: MinecraftTriggerFiltered;
  ['minecraft:on_start_landing']?: MinecraftTriggerFiltered;
  ['minecraft:on_start_takeoff']?: MinecraftTriggerFiltered;
  ['minecraft:on_target_acquired']?: MinecraftTriggerFiltered;
  ['minecraft:on_target_escape']?: MinecraftTriggerFiltered;
  ['minecraft:on_wake_with_owner']?: MinecraftTriggerFiltered;

  // Behavior Components
  ['minecraft:behavior.admire_item']?: BehaviorAdmireItem;
  ['minecraft:behavior.barter']?: any;
  ['minecraft:behavior.beg']?: BehaviorBeg;
  ['minecraft:behavior.break_door']?: any;
  ['minecraft:behavior.breed']?: BehaviorBreed;
  ['minecraft:behavior.defend_trusted_target']?: BehaviorDefendTrustedTarget;
  ['minecraft:behavior.door_interact']?: any;
  ['minecraft:behavior.dragondeath']?: any;
  ['minecraft:behavior.dragonholdingpattern']?: any;
  ['minecraft:behavior.dragonlanding']?: any;
  ['minecraft:behavior.dragonscanning']?: any;
  ['minecraft:behavior.dragontakeoff']?: any;
  ['minecraft:behavior.drink_potion']?: BehaviorDrinkPotion;
  ['minecraft:behavior.eat_carried_item']?: BehaviorEatCarriedItem;
  ['minecraft:behavior.enderman_leave_block']?: any;
  ['minecraft:behavior.enderman_take_block']?: any;
  ['minecraft:behavior.explore_outskirts']?: BehaviorExploreOutskirts;
  ['minecraft:behavior.find_cover']?: BehaviorFindCover;
  ['minecraft:behavior.find_mount']?: BehaviorFindMount;
  ['minecraft:behavior.find_underwater_treasure']?: BehaviorFindUnderwaterTreasure;
  ['minecraft:behavior.flee_sun']?: BehaviorFleeSun;
  ['minecraft:behavior.float']?: any;
  ['minecraft:behavior.float_wander']?: BehaviorFloatWander;
  ['minecraft:behavior.follow_caravan']?: BehaviorFollowCaravan;
  ['minecraft:behavior.follow_mob']?: BehaviorFollow;
  ['minecraft:behavior.follow_owner']?: BehaviorFollow;
  ['minecraft:behavior.follow_parent']?: BehaviorFollowParent;
  ['minecraft:behavior.follow_target_captain']?: BehaviorFollowTargetCaptain;
  ['minecraft:behavior.go_home']?: BehaviorGoHome;
  ['minecraft:behavior.hide']?: BehaviorHide;
  ['minecraft:behavior.hold_ground']?: BehaviorHoldGround;
  ['minecraft:behavior.hurt_by_target']?: BehaviorHurtByTarget;
  ['minecraft:behavior.inspect_bookshelf']?: BehaviorInspectBookshelf;
  ['minecraft:behavior.knockback_roar']?: BehaviorKnockbackRoar;
  ['minecraft:behavior.lay_down']?: BehaviorLayDown;
  ['minecraft:behavior.lay_egg']?: BehaviorLayEgg;
  ['minecraft:behavior.leap_at_target']?: BehaviorLeapAtTarget;
  ['minecraft:behavior.look_at_entity']?: BehaviorLook;
  ['minecraft:behavior.look_at_player']?: BehaviorLook;
  ['minecraft:behavior.look_at_target']?: BehaviorLook;
  ['minecraft:behavior.look_at_trading_player']?: BehaviorLook;
  ['minecraft:behavior.make_love']?: any;
  ['minecraft:behavior.mingle']?: BehaviorMingle;
  ['minecraft:behavior.mount_pathing']?: BehaviorMountPathing;
  ['minecraft:behavior.move_through_village']?: BehaviorMoveThroughVillage;
  ['minecraft:behavior.move_to_block']?: BehaviorMoveToBlock;
  ['minecraft:behavior.move_to_land']?: BehaviorMove;
  ['minecraft:behavior.move_to_lava']?: BehaviorMove;
  ['minecraft:behavior.move_to_liquid']?: BehaviorMoveToLiquid;
  ['minecraft:behavior.move_to_poi']?: BehaviorMoveToPoi;
  ['minecraft:behavior.move_to_random_block']?: BehaviorMoveToRandomBlock;
  ['minecraft:behavior.move_to_village']?: BehaviorMoveToVillage;
  ['minecraft:behavior.move_to_water']?: BehaviorMove;
  ['minecraft:behavior.move_towards_target']?: BehaviorMoveTowardsTarget;
  ['minecraft:behavior.nap']?: BehaviorNap;
  ['minecraft:behavior.nearest_attackable_target']?: BehaviorAttackableTarget;
  ['minecraft:behavior.nearest_prioritized_attackable_target']?: BehaviorAttackableTarget;
  ['minecraft:behavior.ocelot_sit_on_block']?: BehaviorOcelotSitOnBlock;
  ['minecraft:behavior.offer_flower']?: any;
  ['minecraft:behavior.open_door']?: BehaviorOpenDoor;
  ['minecraft:behavior.owner_hurt_by_target']?: BehaviorHurtTarget;
  ['minecraft:behavior.owner_hurt_target']?: BehaviorHurtTarget;
  ['minecraft:behavior.panic']?: BehaviorPanic;
  ['minecraft:behavior.peek']?: any;
  ['minecraft:behavior.pet_sleep_with_owner']?: BehaviorPetSleepWithOwner;
  ['minecraft:behavior.pickup_items']?: BehaviorPickupItems;
  ['minecraft:behavior.play']?: BehaviorPlay;
  ['minecraft:behavior.player_ride_tamed']?: any;
  ['minecraft:behavior.raid_garden']?: BehaviorRaidGarden;
  ['minecraft:behavior.random_breach']?: BehaviorRandomBreach;
  ['minecraft:behavior.random_fly']?: BehaviorRandomFly;
  ['minecraft:behavior.random_hover']?: BehaviorRandomHover;
  ['minecraft:behavior.random_look_around']?: BehaviorRandomLookAround;
  ['minecraft:behavior.random_look_around_and_sit']?: BehaviorRandomLookAroundAndSit;
  ['minecraft:behavior.random_sitting']?: BehaviorRandomSitting;
  ['minecraft:behavior.random_stroll']?: BehaviorRandomStroll;
  ['minecraft:behavior.random_swim']?: BehaviorRandomSwim;
  ['minecraft:behavior.receive_love']?: any;
  ['minecraft:behavior.restrict_open_door']?: any;
  ['minecraft:behavior.restrict_sun']?: any;
  ['minecraft:behavior.rise_to_liquid_level']?: BehaviorRiseToLiquidLevel;
  ['minecraft:behavior.roll']?: BehaviorRoll;
  ['minecraft:behavior.run_around_like_crazy']?: BehaviorRunAroundLikeCrazy;
  ['minecraft:behavior.scared']?: BehaviorScared;
  ['minecraft:behavior.send_event']?: BehaviorSendEvent;
  ['minecraft:behavior.share_items']?: BehaviorShareItems;
  ['minecraft:behavior.silverfish_merge_with_stone']?: any;
  ['minecraft:behavior.silverfish_wake_up_friends']?: any;
  ['minecraft:behavior.skeleton_horse_trap']?: BehaviorSkeletonHorseTrap;
  ['minecraft:behavior.sleep']?: BehaviorSleep;
  ['minecraft:behavior.slime_attack']?: BehaviorSlimeAttack;
  ['minecraft:behavior.snacking']?: BehaviorSnacking;
  ['minecraft:behavior.sneeze']?: BehaviorSneeze;
  ['minecraft:behavior.squid_dive']?: any;
  ['minecraft:behavior.squid_flee']?: any;
  ['minecraft:behavior.squid_idle']?: any;
  ['minecraft:behavior.squid_move_away_from_ground']?: any;
  ['minecraft:behavior.squid_out_of_water']?: any;
  ['minecraft:behavior.stalk_and_pounce_on_target']?: BehaviorStalkAndPounceOnTarget;
  ['minecraft:behavior.stay_while_sitting']?: any;
  ['minecraft:behavior.stomp_turtle_egg']?: BehaviorStompTurtleEgg;
  ['minecraft:behavior.stroll_towards_village']?: BehaviorStrollTowardsVillage;
  ['minecraft:behavior.summon_entity']?: BehaviorSummonEntity;
  ['minecraft:behavior.swell']?: BehaviorSwell;
  ['minecraft:behavior.take_flower']?: any;
  ['minecraft:behavior.tempt']?: BehaviorTempt;
  ['minecraft:behavior.trade_interest']?: BehaviorTradeInterest;
  ['minecraft:behavior.trade_with_player']?: any;
  ['minecraft:behavior.vex_copy_owner_target']?: BehaviorVexCopyOwnerTarget;
  ['minecraft:behavior.vex_random_move']?: any;
  ['minecraft:behavior.wither_random_attack_pos_goal']?: any;
  ['minecraft:behavior.wither_target_highest_damage']?: BehaviorWitherTargetHighestDamage;
  ['minecraft:behavior.work']?: BehaviorWork;
}

// Events
export interface EntityEvents {
  ['minecraft:entity_born']?: EntityEventsReponse;
  ['minecraft:entity_spawned']?: EntityEventsReponse;
  ['minecraft:entity_transformed']?: EntityEventsReponse;
  ['minecraft:on_prime']?: EntityEventsReponse;
  [property_name: string]: EntityEventsReponse;
}

interface EntityEventsReponse extends EventsComponentGroupsController {
  filters?: MinecraftFilters;
  randomize?: EntityEventsRandomize[];
  sequence?: EntityEventsReponse[];
  trigger?: MinecraftTriggerFiltered;
}

interface EntityEventsRandomize extends EventsComponentGroupsController {
  weight?: number;
  trigger?: MinecraftTriggerFiltered;
}

interface EventsComponentGroupsController {
  add?: EventComponentGroups;
  remove?: EventComponentGroups;
}

export interface EventComponentGroups {
  component_groups?: string[];
}
