export type MinecraftSlots =
  | 'none'
  | 'slot.armor'
  | 'slot.armor.chest'
  | 'slot.armor.feet'
  | 'slot.armor.head'
  | 'slot.armor.legs'
  | 'slot.chest'
  | 'slot.enderchest'
  | 'slot.hotbar'
  | 'slot.inventory'
  | 'slot.saddle'
  | 'slot.equippable'
  | 'slot.weapon.mainhand'
  | 'slot.weapond.offhand';
