/** DO NOT EDIT THIS FILE */

import MinecraftBedrockSchemas from '../src/MinecraftBedrockSchemas';

MinecraftBedrockSchemas.generateSchemaFiles('schemas/');
MinecraftBedrockSchemas.generateSettingsFile('.vscode/');
